### ISSUE TITLE
Oi

### ISSUE THREAD

**Issue by NoYaboi** [Vazity1337/Discord-IP-Grabber#5]

**Comment by actuallydoc** [comment]
What is the problem?

**Comment by Wilbatronic** [comment]
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\new1.py", line 31, in <module>
    hook.send(embed=embed)
  File "C:\Users\Admin\Desktop\python\lib\site-packages\dhooks\client.py", line 275, in send
    return self._request('POST', payload, file=file)
  File "C:\Users\Admin\Desktop\python\lib\site-packages\dhooks\client.py", line 388, in _request
    resp.raise_for_status()
  File "C:\Users\Admin\Desktop\python\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://discord.com/api/webhooks/821428994036596816/VWufq86NcTTWD1ia5ER7W6Ki8rnqRAWl-fRpGKWEO0SY-UNPVCeLEQy_hu8QxunygtQt

**Comment by Wilbatronic** [comment]
PAYLOAD LOL ITS A VIRUS

**Comment by DEADSEC-SECURITY** [comment]
> PAYLOAD LOL ITS A VIRUS

Dude, do you even know python or remotely how viruses or programs work? This is everything but malicious.

**Comment by lukehodges** [comment]
maybe have a look at the FUCKING ERROR CODE its a bad requests so check what's wrong with it. and btw you've just given us ur webhooks api

**Comment by NegativeRosie** [comment]
> PAYLOAD LOL ITS A VIRUS

Just a bunch of kids looking to be malicious online. (Script kiddies)
