### ISSUE TITLE
Ajude me

### ISSUE THREAD

**Issue by anajuliadiscord** [Vazity1337/Discord-IP-Grabber#6]
Pra pegar as informaçoes eu presiso mandar o link do webhook para a pessoa?

**Comment by actuallydoc** [comment]
i translated what u said. You have send the file to the person!

**Comment by Wilbatronic** [comment]
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\new1.py", line 31, in <module>
    hook.send(embed=embed)
  File "C:\Users\Admin\Desktop\python\lib\site-packages\dhooks\client.py", line 275, in send
    return self._request('POST', payload, file=file)
  File "C:\Users\Admin\Desktop\python\lib\site-packages\dhooks\client.py", line 388, in _request
    resp.raise_for_status()
  File "C:\Users\Admin\Desktop\python\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://discord.com/api/webhooks/821428994036596816/VWufq86NcTTWD1ia5ER7W6Ki8rnqRAWl-fRpGKWEO0SY-UNPVCeLEQy_hu8QxunygtQt

**Comment by Wilbatronic** [comment]
ITS A VIRUS DONT RUN IT

**Comment by actuallydoc** [comment]
Looking at the code it not even close to being malicious the problem could be that the embed is too big to send

**Comment by actuallydoc** [comment]
From what reason are you calling it a virus?
